In [1]:
import pandas as pd

df = pd.read_csv("sample1.csv", parse_dates=['Date'], date_format='%Y-%m-%d %I-%p')
df

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2     2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3     2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4     2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                   ...     ...     ...     ...     ...     ...         ...
19994 2017-12-01 18:00:00  ETHUSD  452.14  453.88  450.70  452.63  2917055.16
19995 2017-12-01 17:00:00  ETHUSD  452.24  453.20  450.13  452.14  4008631.78
19996 2017-12-01 16:00:00  ETHUSD  449.00  454.00  447.26  452.24  4401582.53
19997 2017-12-01 15:00:00  ETHUSD  451.00  451.00  446.20  449.00  4027856.04
19998 2017-12-01 14:00:00  ETHUSD  457.90  458.00  446.00  451.00  5700243.44

[19999 rows x 7 columns]

In [2]:
df = pd.read_csv("sample1.csv")

df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d %I-%p')
df

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2     2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3     2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4     2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                   ...     ...     ...     ...     ...     ...         ...
19994 2017-12-01 18:00:00  ETHUSD  452.14  453.88  450.70  452.63  2917055.16
19995 2017-12-01 17:00:00  ETHUSD  452.24  453.20  450.13  452.14  4008631.78
19996 2017-12-01 16:00:00  ETHUSD  449.00  454.00  447.26  452.24  4401582.53
19997 2017-12-01 15:00:00  ETHUSD  451.00  451.00  446.20  449.00  4027856.04
19998 2017-12-01 14:00:00  ETHUSD  457.90  458.00  446.00  451.00  5700243.44

[19999 rows x 7 columns]

In [3]:
df.loc[3, 'Date'].day_name()

'Friday'

In [4]:
df.loc[ df['Date']>='2019' ]   # instead do set_index

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2     2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3     2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4     2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                   ...     ...     ...     ...     ...     ...         ...
10504 2019-01-01 04:00:00  ETHUSD  130.75  133.96  130.74  131.96  2791135.37
10505 2019-01-01 03:00:00  ETHUSD  130.06  130.79  130.06  130.75   503732.63
10506 2019-01-01 02:00:00  ETHUSD  130.79  130.88  129.55  130.06   838183.43
10507 2019-01-01 01:00:00  ETHUSD  131.62  131.62  130.77  130.79   434917.99
10508 2019-01-01 00:00:00  ETHUSD  130.53  131.91  130.48  131.62  1067136.21

[10509 rows x 7 columns]

In [5]:
df.set_index('Date', inplace=True)
df

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2017-12-01 18:00:00  ETHUSD  452.14  453.88  450.70  452.63  2917055.16
2017-12-01 17:00:00  ETHUSD  452.24  453.20  450.13  452.14  4008631.78
2017-12-01 16:00:00  ETHUSD  449.00  454.00  447.26  452.24  4401582.53
2017-12-01 15:00:00  ETHUSD  451.00  451.00  446.20  449.00  4027856.04
2017-12-01 14:00:00  ETHUSD  457.90  458.00  446.00  451.00  5700243.44

[19999 rows x 6 columns]

In [6]:
df['2018': '2020']

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2018-01-01 04:00:00  ETHUSD  739.70  748.07  733.02  747.90  3180304.69
2018-01-01 03:00:00  ETHUSD  730.01  739.70  728.66  739.70  3461348.11
2018-01-01 02:00:00  ETHUSD  730.02  730.50  727.14  730.01  2950627.37
2018-01-01 01:00:00  ETHUSD  734.59  735.10  730.01  730.02  1886624.01
2018-01-01 00:00:00  ETHUSD  741.27  741.27  733.69  734.59  2697546.48

[19269 rows x 6 columns]

In [7]:
df['2018': '2020'].max()

Symbol         ETHUSD
Open          1418.61
High          1419.96
Low           1388.99
Close         1418.61
Volume    85697897.38
dtype: object

In [8]:
df['Low'].resample("Q").min()

Date
2017-12-31    415.01
2018-03-31    365.00
2018-06-30    360.00
2018-09-30    167.00
2018-12-31     80.60
2019-03-31    100.15
2019-06-30    138.81
2019-09-30    152.11
2019-12-31    116.25
2020-03-31     90.00
Freq: Q-DEC, Name: Low, dtype: float64

In [9]:
df[['Low', 'High']].resample("Q").min()

               Low    High
Date
2017-12-31  415.01  427.48
2018-03-31  365.00  377.52
2018-06-30  360.00  366.96
2018-09-30  167.00  171.11
2018-12-31   80.60   82.00
2019-03-31  100.15  101.70
2019-06-30  138.81  140.48
2019-09-30  152.11  161.14
2019-12-31  116.25  121.76
2020-03-31   90.00  110.99

In [10]:
df.resample("Q").count()

            Symbol  Open  High   Low  Close  Volume
Date
2017-12-31     730   730   730   730    730     730
2018-03-31    2160  2160  2160  2160   2160    2160
2018-06-30    2184  2184  2184  2184   2184    2184
2018-09-30    2208  2208  2208  2208   2208    2208
2018-12-31    2208  2208  2208  2208   2208    2208
2019-03-31    2160  2160  2160  2160   2160    2160
2019-06-30    2184  2184  2184  2184   2184    2184
2019-09-30    2208  2208  2208  2208   2208    2208
2019-12-31    2208  2208  2208  2208   2208    2208
2020-03-31    1749  1749  1749  1749   1749    1749

In [11]:
df.resample('Q').agg({"High": "mean", "Low": "last", "Volume": "first", "Open": "std"})

                  High     Low      Volume        Open
Date
2017-12-31  640.392548  740.33  5700243.44  133.961479
2018-03-31  870.224167  392.16  2697546.48  228.473363
2018-06-30  575.531030  447.20  1795558.20  113.887381
2018-09-30  340.336155  231.80  1081687.58  103.160827
2018-12-31  161.971970  130.20   915971.56   49.253602
2019-03-31  129.819662  141.10  1067136.21   13.935357
2019-06-30  220.344460  286.00  1641646.71   53.301920
2019-09-30  212.671993  177.54  4209855.92   37.629161
2019-12-31  163.520376  128.14   710407.18   21.554625
2020-03-31  199.030543  126.87   245119.91   45.921111

In [12]:
date1 = pd.date_range(start="2020-01-01", periods=10, freq="S", tz='Asia/kolkata') ## second
date1

DatetimeIndex(['2020-01-01 00:00:00+05:30', '2020-01-01 00:00:01+05:30',
               '2020-01-01 00:00:02+05:30', '2020-01-01 00:00:03+05:30',
               '2020-01-01 00:00:04+05:30', '2020-01-01 00:00:05+05:30',
               '2020-01-01 00:00:06+05:30', '2020-01-01 00:00:07+05:30',
               '2020-01-01 00:00:08+05:30', '2020-01-01 00:00:09+05:30'],
              dtype='datetime64[ns, Asia/Kolkata]', freq='S')

In [13]:
date1 = pd.date_range(start="2020-01-01", periods=10, freq="W-Thu", tz='Asia/kolkata') ## thurday weekly
date1

DatetimeIndex(['2020-01-02 00:00:00+05:30', '2020-01-09 00:00:00+05:30',
               '2020-01-16 00:00:00+05:30', '2020-01-23 00:00:00+05:30',
               '2020-01-30 00:00:00+05:30', '2020-02-06 00:00:00+05:30',
               '2020-02-13 00:00:00+05:30', '2020-02-20 00:00:00+05:30',
               '2020-02-27 00:00:00+05:30', '2020-03-05 00:00:00+05:30'],
              dtype='datetime64[ns, Asia/Kolkata]', freq='W-THU')

In [14]:
date1 = pd.date_range(start="2020-01-01", periods=10, freq="MS", tz='Asia/kolkata') ## month start
date1

DatetimeIndex(['2020-01-01 00:00:00+05:30', '2020-02-01 00:00:00+05:30',
               '2020-03-01 00:00:00+05:30', '2020-04-01 00:00:00+05:30',
               '2020-05-01 00:00:00+05:30', '2020-06-01 00:00:00+05:30',
               '2020-07-01 00:00:00+05:30', '2020-08-01 00:00:00+05:30',
               '2020-09-01 00:00:00+05:30', '2020-10-01 00:00:00+05:30'],
              dtype='datetime64[ns, Asia/Kolkata]', freq='MS')

In [15]:
date1 = pd.date_range(start="2020-01-01", periods=10, freq="min", tz='Asia/kolkata') ## minute
date1

DatetimeIndex(['2020-01-01 00:00:00+05:30', '2020-01-01 00:01:00+05:30',
               '2020-01-01 00:02:00+05:30', '2020-01-01 00:03:00+05:30',
               '2020-01-01 00:04:00+05:30', '2020-01-01 00:05:00+05:30',
               '2020-01-01 00:06:00+05:30', '2020-01-01 00:07:00+05:30',
               '2020-01-01 00:08:00+05:30', '2020-01-01 00:09:00+05:30'],
              dtype='datetime64[ns, Asia/Kolkata]', freq='T')

In [16]:
df

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2017-12-01 18:00:00  ETHUSD  452.14  453.88  450.70  452.63  2917055.16
2017-12-01 17:00:00  ETHUSD  452.24  453.20  450.13  452.14  4008631.78
2017-12-01 16:00:00  ETHUSD  449.00  454.00  447.26  452.24  4401582.53
2017-12-01 15:00:00  ETHUSD  451.00  451.00  446.20  449.00  4027856.04
2017-12-01 14:00:00  ETHUSD  457.90  458.00  446.00  451.00  5700243.44

[19999 rows x 6 columns]

In [17]:
df.between_time("10:30" , "11:00")         # start_time, end_time

                     Symbol    Open    High     Low   Close       Volume
Date
2020-03-13 11:00:00  ETHUSD  132.60  133.17  126.01  128.93   3311080.29
2020-03-12 11:00:00  ETHUSD  134.67  151.19  126.29  136.83  16556632.81
2020-03-11 11:00:00  ETHUSD  197.37  198.44  195.83  196.67    664974.80
2020-03-10 11:00:00  ETHUSD  203.47  205.38  202.36  203.23   1871438.76
2020-03-09 11:00:00  ETHUSD  203.68  203.68  199.38  201.16   3145976.84
...                     ...     ...     ...     ...     ...          ...
2017-12-06 11:00:00  ETHUSD  455.02  455.99  451.50  455.98   3460446.79
2017-12-05 11:00:00  ETHUSD  462.66  463.50  460.10  462.00   1869239.19
2017-12-04 11:00:00  ETHUSD  463.00  465.50  458.90  459.25   2083171.11
2017-12-03 11:00:00  ETHUSD  467.20  474.96  467.09  474.94   3814495.82
2017-12-02 11:00:00  ETHUSD  466.24  468.43  461.00  462.25   2680953.00

[833 rows x 6 columns]

In [18]:
df.between_time("10:30:20" , "11:00:30")         # start_time, end_time

                     Symbol    Open    High     Low   Close       Volume
Date
2020-03-13 11:00:00  ETHUSD  132.60  133.17  126.01  128.93   3311080.29
2020-03-12 11:00:00  ETHUSD  134.67  151.19  126.29  136.83  16556632.81
2020-03-11 11:00:00  ETHUSD  197.37  198.44  195.83  196.67    664974.80
2020-03-10 11:00:00  ETHUSD  203.47  205.38  202.36  203.23   1871438.76
2020-03-09 11:00:00  ETHUSD  203.68  203.68  199.38  201.16   3145976.84
...                     ...     ...     ...     ...     ...          ...
2017-12-06 11:00:00  ETHUSD  455.02  455.99  451.50  455.98   3460446.79
2017-12-05 11:00:00  ETHUSD  462.66  463.50  460.10  462.00   1869239.19
2017-12-04 11:00:00  ETHUSD  463.00  465.50  458.90  459.25   2083171.11
2017-12-03 11:00:00  ETHUSD  467.20  474.96  467.09  474.94   3814495.82
2017-12-02 11:00:00  ETHUSD  466.24  468.43  461.00  462.25   2680953.00

[833 rows x 6 columns]

In [19]:
df.truncate("2020-01-01","2020-01-05")                 # before, after => only give within that range

                     Symbol    Open    High     Low   Close     Volume
Date
2020-01-05 00:00:00  ETHUSD  134.14  135.09  134.14  134.66  255184.67
2020-01-04 23:00:00  ETHUSD  134.11  134.36  133.81  134.14  188707.61
2020-01-04 22:00:00  ETHUSD  133.95  134.37  133.68  134.11  175358.35
2020-01-04 21:00:00  ETHUSD  133.93  134.38  133.53  133.95  149581.66
2020-01-04 20:00:00  ETHUSD  133.72  134.00  133.40  133.93   98575.89
...                     ...     ...     ...     ...     ...        ...
2020-01-01 04:00:00  ETHUSD  129.57  130.00  129.50  129.56  702786.82
2020-01-01 03:00:00  ETHUSD  130.37  130.44  129.38  129.57  496704.23
2020-01-01 02:00:00  ETHUSD  130.14  130.50  129.91  130.37  396315.72
2020-01-01 01:00:00  ETHUSD  128.34  130.14  128.32  130.14  635419.40
2020-01-01 00:00:00  ETHUSD  128.54  128.54  128.12  128.34  245119.91

[97 rows x 6 columns]

In [20]:
df.truncate("2020-01-01 03:00:00","2020-01-04 04:00:00")        # before, after => only give within that range

                     Symbol    Open    High     Low   Close     Volume
Date
2020-01-04 04:00:00  ETHUSD  133.28  133.70  132.84  133.45   65056.84
2020-01-04 03:00:00  ETHUSD  133.22  133.39  132.98  133.28  108029.29
2020-01-04 02:00:00  ETHUSD  132.89  133.22  132.59  133.22  185610.06
2020-01-04 01:00:00  ETHUSD  133.65  133.66  132.68  132.89  167436.97
2020-01-04 00:00:00  ETHUSD  134.17  134.73  133.35  133.65  403925.92
...                     ...     ...     ...     ...     ...        ...
2020-01-01 07:00:00  ETHUSD  130.00  130.25  129.80  129.87  112620.14
2020-01-01 06:00:00  ETHUSD  129.83  130.25  129.82  130.00  118328.64
2020-01-01 05:00:00  ETHUSD  129.56  129.94  129.47  129.83  232163.70
2020-01-01 04:00:00  ETHUSD  129.57  130.00  129.50  129.56  702786.82
2020-01-01 03:00:00  ETHUSD  130.37  130.44  129.38  129.57  496704.23

[74 rows x 6 columns]

In [21]:
df["Low"].shift(1)               # lag

Date
2020-03-13 20:00:00       NaN
2020-03-13 19:00:00    126.87
2020-03-13 18:00:00    117.10
2020-03-13 17:00:00    115.50
2020-03-13 16:00:00    121.63
                        ...
2017-12-01 18:00:00    451.16
2017-12-01 17:00:00    450.70
2017-12-01 16:00:00    450.13
2017-12-01 15:00:00    447.26
2017-12-01 14:00:00    446.20
Name: Low, Length: 19999, dtype: float64

In [22]:
df.shift(1)               # lag

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00    None     NaN     NaN     NaN     NaN         NaN
2020-03-13 19:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 18:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 17:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 16:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
...                     ...     ...     ...     ...     ...         ...
2017-12-01 18:00:00  ETHUSD  452.63  457.51  451.16  456.00  5821744.88
2017-12-01 17:00:00  ETHUSD  452.14  453.88  450.70  452.63  2917055.16
2017-12-01 16:00:00  ETHUSD  452.24  453.20  450.13  452.14  4008631.78
2017-12-01 15:00:00  ETHUSD  449.00  454.00  447.26  452.24  4401582.53
2017-12-01 14:00:00  ETHUSD  451.00  451.00  446.20  449.00  4027856.04

[19999 rows x 6 columns]

In [23]:
df["Low"].shift(-1)               # lead

Date
2020-03-13 20:00:00    117.10
2020-03-13 19:00:00    115.50
2020-03-13 18:00:00    121.63
2020-03-13 17:00:00    120.17
2020-03-13 16:00:00    116.06
                        ...
2017-12-01 18:00:00    450.13
2017-12-01 17:00:00    447.26
2017-12-01 16:00:00    446.20
2017-12-01 15:00:00    446.00
2017-12-01 14:00:00       NaN
Name: Low, Length: 19999, dtype: float64

In [24]:
df['3_steps_back'] = df['Low'].shift(3)
df['3_steps_back']

Date
2020-03-13 20:00:00       NaN
2020-03-13 19:00:00       NaN
2020-03-13 18:00:00       NaN
2020-03-13 17:00:00    126.87
2020-03-13 16:00:00    117.10
                        ...
2017-12-01 18:00:00    461.88
2017-12-01 17:00:00    456.00
2017-12-01 16:00:00    451.16
2017-12-01 15:00:00    450.70
2017-12-01 14:00:00    450.13
Name: 3_steps_back, Length: 19999, dtype: float64

In [25]:
df['Low'] - df['Low'].shift(1)             # difference from previous row

Date
2020-03-13 20:00:00     NaN
2020-03-13 19:00:00   -9.77
2020-03-13 18:00:00   -1.60
2020-03-13 17:00:00    6.13
2020-03-13 16:00:00   -1.46
                       ...
2017-12-01 18:00:00   -0.46
2017-12-01 17:00:00   -0.57
2017-12-01 16:00:00   -2.87
2017-12-01 15:00:00   -1.06
2017-12-01 14:00:00   -0.20
Name: Low, Length: 19999, dtype: float64

In [26]:
df.shift(1, axis=1)  # shifts all columns to the right

,Symbol,Open,High,Low,Close,Volume,3_steps_back
Date,,,,,,,
2020-03-13 20:00:00,None,ETHUSD,129.94,131.82,126.87,128.71,1940673.93
2020-03-13 19:00:00,None,ETHUSD,119.51,132.02,117.10,129.94,7579741.09
2020-03-13 18:00:00,None,ETHUSD,124.47,124.85,115.50,119.51,4898735.81
2020-03-13 17:00:00,None,ETHUSD,124.08,127.42,121.63,124.47,2753450.92
2020-03-13 16:00:00,None,ETHUSD,124.85,129.51,120.17,124.08,4461424.71
...,...,...,...,...,...,...,...
2017-12-01 18:00:00,None,ETHUSD,452.14,453.88,450.70,452.63,2917055.16
2017-12-01 17:00:00,None,ETHUSD,452.24,453.20,450.13,452.14,4008631.78
2017-12-01 16:00:00,None,ETHUSD,449.00,454.00,447.26,452.24,4401582.53
2017-12-01 15:00:00,None,ETHUSD,451.00,451.00,446.20,449.00,4027856.04
2017-12-01 14:00:00,None,ETHUSD,457.90,458.00,446.00,451.00,5700243.44

In [27]:
df.shift(-1)                   # lead

,Symbol,Open,High,Low,Close,Volume,3_steps_back
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,NaN
2020-03-13 19:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,NaN
2020-03-13 18:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,126.87
2020-03-13 17:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,117.10
2020-03-13 16:00:00,ETHUSD,128.39,128.90,116.06,124.85,7378976.00,115.50
...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,456.00
2017-12-01 17:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,451.16
2017-12-01 16:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,450.70
2017-12-01 15:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,450.13
2017-12-01 14:00:00,None,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df

,Symbol,Open,High,Low,Close,Volume,3_steps_back
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,NaN
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,NaN
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,NaN
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,126.87
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,117.10
...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.14,453.88,450.70,452.63,2917055.16,461.88
2017-12-01 17:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,456.00
2017-12-01 16:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,451.16
2017-12-01 15:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,450.70
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,450.13

In [29]:
df.drop("3_steps_back", axis=1)
df

,Symbol,Open,High,Low,Close,Volume,3_steps_back
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,NaN
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,NaN
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,NaN
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,126.87
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,117.10
...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.14,453.88,450.70,452.63,2917055.16,461.88
2017-12-01 17:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,456.00
2017-12-01 16:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,451.16
2017-12-01 15:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,450.70
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,450.13

In [30]:
df.drop("3_steps_back", axis=1, inplace=True)
df

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2017-12-01 18:00:00  ETHUSD  452.14  453.88  450.70  452.63  2917055.16
2017-12-01 17:00:00  ETHUSD  452.24  453.20  450.13  452.14  4008631.78
2017-12-01 16:00:00  ETHUSD  449.00  454.00  447.26  452.24  4401582.53
2017-12-01 15:00:00  ETHUSD  451.00  451.00  446.20  449.00  4027856.04
2017-12-01 14:00:00  ETHUSD  457.90  458.00  446.00  451.00  5700243.44

[19999 rows x 6 columns]

In [31]:
df['High'].rolling(window=3).mean()

Date
2020-03-13 20:00:00           NaN
2020-03-13 19:00:00           NaN
2020-03-13 18:00:00    129.563333
2020-03-13 17:00:00    128.096667
2020-03-13 16:00:00    127.260000
                          ...
2017-12-01 18:00:00    459.370000
2017-12-01 17:00:00    454.863333
2017-12-01 16:00:00    453.693333
2017-12-01 15:00:00    452.733333
2017-12-01 14:00:00    454.333333
Name: High, Length: 19999, dtype: float64

In [32]:
df[['High', 'Low', 'Volume']].rolling(window=3).mean()

                           High         Low        Volume
Date
2020-03-13 20:00:00         NaN         NaN           NaN
2020-03-13 19:00:00         NaN         NaN           NaN
2020-03-13 18:00:00  129.563333  119.823333  4.806384e+06
2020-03-13 17:00:00  128.096667  118.076667  5.077309e+06
2020-03-13 16:00:00  127.260000  119.100000  4.037870e+06
...                         ...         ...           ...
2017-12-01 18:00:00  459.370000  452.620000  5.245907e+06
2017-12-01 17:00:00  454.863333  450.663333  4.249144e+06
2017-12-01 16:00:00  453.693333  449.363333  3.775756e+06
2017-12-01 15:00:00  452.733333  447.863333  4.146023e+06
2017-12-01 14:00:00  454.333333  446.486667  4.709894e+06

[19999 rows x 3 columns]

In [33]:
df['High'].rolling(window=3,center=True).mean()

Date
2020-03-13 20:00:00           NaN
2020-03-13 19:00:00    129.563333
2020-03-13 18:00:00    128.096667
2020-03-13 17:00:00    127.260000
2020-03-13 16:00:00    128.610000
                          ...
2017-12-01 18:00:00    454.863333
2017-12-01 17:00:00    453.693333
2017-12-01 16:00:00    452.733333
2017-12-01 15:00:00    454.333333
2017-12-01 14:00:00           NaN
Name: High, Length: 19999, dtype: float64

In [34]:
df['High_diff'] = df['High'].diff()
df

,Symbol,Open,High,Low,Close,Volume,High_diff
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,NaN
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,0.20
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,-7.17
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,2.57
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,2.09
...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.14,453.88,450.70,452.63,2917055.16,-3.63
2017-12-01 17:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,-0.68
2017-12-01 16:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,0.80
2017-12-01 15:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,-3.00
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00

In [35]:
df['High_diffby2'] = df['High'].diff(periods=2)  #  124.85- 131.82, 127.42-132.02 and so on
df

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2
Date,,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,NaN,NaN
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,0.20,NaN
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,-7.17,-6.97
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,2.57,-4.60
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,2.09,4.66
...,...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.14,453.88,450.70,452.63,2917055.16,-3.63,-12.84
2017-12-01 17:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,-0.68,-4.31
2017-12-01 16:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,0.80,0.12
2017-12-01 15:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,-3.00,-2.20
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00,4.00

In [39]:
df['column_diff'] = df[['High', 'Low']].diff(axis=1)['Low']      # High => gives NaN
df

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2,column_diff
Date,,,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,NaN,NaN,-4.95
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,0.20,NaN,-14.92
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,-7.17,-6.97,-9.35
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,2.57,-4.60,-5.79
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,2.09,4.66,-9.34
...,...,...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.14,453.88,450.70,452.63,2917055.16,-3.63,-12.84,-3.18
2017-12-01 17:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,-0.68,-4.31,-3.07
2017-12-01 16:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,0.80,0.12,-6.74
2017-12-01 15:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,-3.00,-2.20,-4.80
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00,4.00,-12.00

In [41]:
df['column_diff'] = df['High'] - df['Low']
df

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2,column_diff
Date,,,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,NaN,NaN,4.95
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,0.20,NaN,14.92
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,-7.17,-6.97,9.35
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,2.57,-4.60,5.79
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,2.09,4.66,9.34
...,...,...,...,...,...,...,...,...,...
2017-12-01 18:00:00,ETHUSD,452.14,453.88,450.70,452.63,2917055.16,-3.63,-12.84,3.18
2017-12-01 17:00:00,ETHUSD,452.24,453.20,450.13,452.14,4008631.78,-0.68,-4.31,3.07
2017-12-01 16:00:00,ETHUSD,449.00,454.00,447.26,452.24,4401582.53,0.80,0.12,6.74
2017-12-01 15:00:00,ETHUSD,451.00,451.00,446.20,449.00,4027856.04,-3.00,-2.20,4.80
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00,4.00,12.00

In [44]:
df.asfreq("B")         # business day

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2,column_diff
Date,,,,,,,,,
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00,4.00,12.00
2017-12-04 14:00:00,ETHUSD,460.78,466.43,457.07,465.00,2205607.85,1.32,1.75,9.36
2017-12-05 14:00:00,ETHUSD,460.04,462.00,459.44,461.01,3450790.73,0.38,1.15,2.56
2017-12-06 14:00:00,ETHUSD,452.00,452.49,451.50,451.50,5184503.90,-0.01,8.02,0.99
2017-12-07 14:00:00,ETHUSD,436.48,444.36,431.08,444.10,6412440.43,-3.64,6.36,13.28
...,...,...,...,...,...,...,...,...,...
2020-03-09 14:00:00,ETHUSD,202.45,203.55,196.58,197.77,5236222.63,4.73,2.74,6.97
2020-03-10 14:00:00,ETHUSD,202.85,205.26,202.57,203.42,1088440.64,1.84,5.46,2.69
2020-03-11 14:00:00,ETHUSD,196.87,197.37,193.05,193.92,1874611.01,2.49,3.40,4.32
2020-03-12 14:00:00,ETHUSD,135.39,144.00,131.00,140.79,8788199.04,2.42,1.51,13.00
2020-03-13 14:00:00,ETHUSD,134.03,137.90,125.50,128.39,3733916.89,9.00,8.39,12.40

In [47]:
df.asfreq('D', method='pad')        # daily,  fills missing data using the previous available value

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2,column_diff
Date,,,,,,,,,
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00,4.00,12.00
2017-12-02 14:00:00,ETHUSD,463.50,464.50,451.21,459.45,6032715.96,2.55,4.80,13.29
2017-12-03 14:00:00,ETHUSD,477.89,477.96,473.16,476.96,2379435.35,-1.81,-3.82,4.80
2017-12-04 14:00:00,ETHUSD,460.78,466.43,457.07,465.00,2205607.85,1.32,1.75,9.36
2017-12-05 14:00:00,ETHUSD,460.04,462.00,459.44,461.01,3450790.73,0.38,1.15,2.56
...,...,...,...,...,...,...,...,...,...
2020-03-09 14:00:00,ETHUSD,202.45,203.55,196.58,197.77,5236222.63,4.73,2.74,6.97
2020-03-10 14:00:00,ETHUSD,202.85,205.26,202.57,203.42,1088440.64,1.84,5.46,2.69
2020-03-11 14:00:00,ETHUSD,196.87,197.37,193.05,193.92,1874611.01,2.49,3.40,4.32
2020-03-12 14:00:00,ETHUSD,135.39,144.00,131.00,140.79,8788199.04,2.42,1.51,13.00
2020-03-13 14:00:00,ETHUSD,134.03,137.90,125.50,128.39,3733916.89,9.00,8.39,12.40

In [49]:
df.asfreq('QS')              # quarterly start

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2,column_diff
Date,,,,,,,,,
2018-01-01 14:00:00,ETHUSD,742.50,744.50,732.00,744.49,2396466.07,-4.50,-3.50,12.50
2018-04-01 14:00:00,ETHUSD,368.39,368.52,360.00,365.00,5195902.65,1.56,-11.23,8.52
2018-07-01 14:00:00,ETHUSD,449.16,449.16,445.00,445.81,737871.58,-0.70,-0.99,4.16
2018-10-01 14:00:00,ETHUSD,227.30,227.72,223.45,226.75,2347461.02,0.47,-1.06,4.27
2019-01-01 14:00:00,ETHUSD,134.65,134.65,133.80,133.81,806604.71,0.84,1.15,0.85
2019-04-01 14:00:00,ETHUSD,142.07,142.49,141.56,141.68,688765.09,0.61,0.83,0.93
2019-07-01 14:00:00,ETHUSD,285.50,289.37,280.15,280.76,3386287.24,2.63,1.89,9.22
2019-10-01 14:00:00,ETHUSD,179.90,180.23,178.18,178.78,377620.74,0.45,-0.27,2.05
2020-01-01 14:00:00,ETHUSD,131.41,132.05,130.93,131.66,143192.12,-0.10,-0.51,1.12

In [51]:
df.asfreq('12H')

,Symbol,Open,High,Low,Close,Volume,High_diff,High_diffby2,column_diff
Date,,,,,,,,,
2017-12-01 14:00:00,ETHUSD,457.90,458.00,446.00,451.00,5700243.44,7.00,4.00,12.00
2017-12-02 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-02 14:00:00,ETHUSD,463.50,464.50,451.21,459.45,6032715.96,2.55,4.80,13.29
2017-12-03 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-12-03 14:00:00,ETHUSD,477.89,477.96,473.16,476.96,2379435.35,-1.81,-3.82,4.80
...,...,...,...,...,...,...,...,...,...
2020-03-11 14:00:00,ETHUSD,196.87,197.37,193.05,193.92,1874611.01,2.49,3.40,4.32
2020-03-12 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-12 14:00:00,ETHUSD,135.39,144.00,131.00,140.79,8788199.04,2.42,1.51,13.00
2020-03-13 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-13 14:00:00,ETHUSD,134.03,137.90,125.50,128.39,3733916.89,9.00,8.39,12.40